# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5

    working_directory: /go/src/github.com/vahidhashemi/tracert
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go build main.go models.go
      - store_artifacts:
          path: /tmp/
          destination: trace
  test:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/vahidhashemi/tracert
    steps:
      - checkout
      - run: go test -v ./...

workflows:
  version: 2
  build_and_test:
      jobs:
        - build
        - test
